# Site settings
title: CaritatHelp Styleguide
email: jerome.coupe@webstoemp.com
description: Style guide for CaritatHelp
baseurl: ""
url: "http://caritathelp.github.io" # the base hostname & protocol for your site
twitter_username: caritathelp
github_username:  caritathelp

# Collections
collections:
  components:
    output: true

# Front Matter Defaults

# General settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
sass:
  sass_dir: _sass
  style: :compressed
